# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            minitrue
tagline:          'true to the times'
description:      'A collection of thoughts, opinions and useless trivia.'
url:              http://minitrue.in
baseurl:          /

author:
  name:           'The Rambling Sapien'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/minitruein/minitruein.github.io
